#!/usr/bin/env python3
"""Tray icon para talk2ai."""

import os
import sys
import subprocess
import threading
from datetime import datetime
from pathlib import Path

from PyQt6.QtWidgets import (QApplication, QSystemTrayIcon, QMenu,
                              QWidget, QVBoxLayout, QHBoxLayout,
                              QTextEdit, QTextBrowser, QPushButton,
                              QInputDialog, QMessageBox)
from PyQt6.QtGui import (QIcon, QPixmap, QPainter, QColor, QBrush,
                         QFont, QAction, QPainterPath, QTransform, QTextCursor,
                         QRadialGradient, QLinearGradient)
from PyQt6.QtCore import QTimer, Qt, QRectF, pyqtSignal, QObject, QFileSystemWatcher, QByteArray
from PyQt6.QtSvg import QSvgRenderer

HANDY_DB           = Path.home() / ".local/share/com.pais.handy/history.db"
TALK2AI_DIR        = Path.home() / ".talk2ai"
MODE_FILE          = TALK2AI_DIR / "mode"
DRIVER_FILE        = TALK2AI_DIR / "driver"
STATE_FILE         = TALK2AI_DIR / "ai-state"
DEBUG_ENABLED_FILE = TALK2AI_DIR / "debug"
DEBUG_LOG_FILE     = TALK2AI_DIR / "debug.log"
MODEL_FILE         = TALK2AI_DIR / "model"
OLLAMA_HOST_FILE   = TALK2AI_DIR / "ollama-host"
SERVICE            = "talk2ai.service"

# Curva de latido: doble pulso rápido + pausa (escala relativa)
HEARTBEAT_FRAMES = [1.0, 1.18, 1.0, 1.10, 1.0, 1.0, 1.0, 1.0]

# Logo oficial Gemini 2025 (estrella 4 puntas con gradiente azul→violeta)
_GEMINI_STAR_PATH = (
    "M32.4473 0C33.1278 0 33.7197 0.464783 33.8857 1.125C34.3947 3.14441 35.0586 5.11414 "
    "35.8848 7.03027C38.0369 12.0299 40.99 16.406 44.7393 20.1553C48.4903 23.9045 52.8647 "
    "26.8576 57.8643 29.0098C59.7821 29.8359 61.7502 30.4998 63.7695 31.0088C64.4297 31.1748 "
    "64.8944 31.7668 64.8945 32.4473C64.8945 33.1278 64.4298 33.7198 63.7695 33.8857C61.7502 "
    "34.3947 59.7803 35.0586 57.8643 35.8848C52.8646 38.037 48.4885 40.99 44.7393 44.7393C40.99 "
    "48.4904 38.037 52.8646 35.8848 57.8643C35.0586 59.7822 34.3947 61.7502 33.8857 63.7695C"
    "33.7198 64.4298 33.1278 64.8945 32.4473 64.8945C31.7668 64.8944 31.1748 64.4297 31.0088 "
    "63.7695C30.4998 61.7502 29.8359 59.7803 29.0098 57.8643C26.8576 52.8647 23.9063 48.4885 "
    "20.1553 44.7393C16.4041 40.99 12.0299 38.0369 7.03027 35.8848C5.1123 35.0586 3.14441 "
    "34.3947 1.125 33.8857C0.464783 33.7197 0 33.1278 0 32.4473C8.67651e-05 31.7668 0.464826 "
    "31.1748 1.125 31.0088C3.14442 30.4998 5.11413 29.836 7.03027 29.0098C12.03 26.8575 16.406 "
    "23.9046 20.1553 20.1553C23.9046 16.406 26.8575 12.03 29.0098 7.03027C29.836 5.11229 "
    "30.4998 3.14442 31.0088 1.125C31.1748 0.464826 31.7668 8.67651e-05 32.4473 0Z"
)
GEMINI_STAR_SVG = (
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64.8945 64.8945">'
    '<defs><linearGradient id="g" x1="18.4474" y1="43.4202" x2="52.1528" y2="15.0035" '
    'gradientUnits="userSpaceOnUse">'
    '<stop offset="0" stop-color="#4893FC"/>'
    '<stop offset="0.27" stop-color="#4893FC"/>'
    '<stop offset="0.77" stop-color="#969DFF"/>'
    '<stop offset="1" stop-color="#BD99FE"/>'
    '</linearGradient></defs>'
    f'<path fill="url(#g)" d="{_GEMINI_STAR_PATH}"/>'
    '</svg>'
)
OLLAMA_SVG = (
    '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="294 159 1405.09 1857.06">'
    '<path d="M599.877 159.522C582.544 162.322 561.744 171.388 547.077 182.588C502.677 216.322 '
    '468.277 287.922 453.744 377.122C448.277 410.855 444.544 457.655 444.544 493.388C444.544 '
    '535.522 449.477 589.388 456.544 626.589C458.144 634.855 458.944 642.188 458.277 642.722C'
    '457.744 643.255 451.211 648.588 443.877 654.455C418.811 674.455 390.144 705.255 370.411 '
    '733.388C332.544 787.122 308.011 848.188 297.744 914.322C293.744 940.455 292.677 993.255 '
    '295.877 1019.39C302.944 1079.66 321.077 1130.59 352.144 1177.26L362.277 1192.32L359.344 '
    '1197.26C338.544 1232.19 320.811 1282.72 312.544 1331.26C306.011 1369.66 305.211 1379.92 '
    '305.211 1431.39C305.211 1483.26 305.877 1493.52 312.011 1529.39C319.344 1572.32 334.277 '
    '1617.79 350.944 1648.06C356.411 1657.92 369.744 1678.46 371.344 1679.52C371.877 1679.79 '
    '370.277 1684.72 367.744 1690.46C348.544 1732.46 332.144 1788.32 325.344 1835.39C320.544 '
    '1867.66 319.877 1878.06 319.877 1912.06C319.877 1955.39 322.277 1976.46 331.344 2010.99L'
    '332.677 2016.06H389.744H446.944L443.211 2008.99C420.144 1966.32 418.011 1887.12 437.877 '
    '1808.06C446.944 1771.52 457.211 1744.72 476.411 1707.79L487.877 1685.39V1671.66C487.877 '
    '1658.86 487.611 1657.39 483.477 1648.99C480.277 1642.59 476.011 1637.12 468.411 1629.66C'
    '455.477 1617.12 446.144 1603.92 438.677 1587.66C405.877 1516.46 399.477 1410.72 422.544 '
    '1320.59C432.144 1282.99 448.011 1249.52 464.677 1231.26C476.011 1218.72 481.877 1204.72 '
    '481.877 1190.19C481.877 1175.12 476.544 1162.72 464.544 1149.79C430.144 1112.99 408.944 '
    '1068.19 401.344 1016.06C390.544 941.788 410.144 860.855 454.677 796.722C498.277 733.788 '
    '559.477 693.388 627.877 682.589C643.211 680.055 671.877 680.455 687.877 683.388C705.344 '
    '686.455 716.277 685.522 727.477 680.188C741.344 673.655 748.277 665.522 756.411 646.855C'
    '763.611 630.188 769.211 621.122 784.277 602.322C802.411 579.788 819.877 564.455 847.877 '
    '545.922C879.877 524.988 916.277 509.788 952.544 502.455C965.744 499.788 971.877 499.388 '
    '996.544 499.388C1021.21 499.388 1027.34 499.788 1040.54 502.455C1093.74 513.255 1146.54 '
    '540.722 1188.68 579.655C1197.74 588.055 1219.48 614.988 1226.41 626.188C1229.08 630.588 '
    '1233.74 639.922 1236.68 646.855C1244.81 665.522 1251.74 673.655 1265.61 680.188C1276.41 '
    '685.388 1287.74 686.455 1304.54 683.655C1331.08 679.122 1351.48 679.522 1377.48 684.855C'
    '1466.01 702.722 1543.08 775.655 1577.21 873.388C1606.94 959.122 1598.54 1048.86 1554.28 '
    '1117.39C1546.81 1128.99 1539.34 1138.32 1528.54 1149.79C1505.21 1174.72 1505.21 1205.66 '
    '1528.41 1231.26C1566.54 1272.99 1590.41 1375.66 1583.21 1466.19C1578.41 1525.92 1563.08 '
    '1579.39 1542.01 1609.66C1538.28 1614.99 1530.54 1624.06 1524.68 1629.66C1517.08 1637.12 '
    '1512.81 1642.59 1509.61 1648.99C1505.48 1657.39 1505.21 1658.86 1505.21 1671.66V1685.39L'
    '1516.68 1707.79C1535.88 1744.72 1546.14 1771.52 1555.21 1808.06C1574.81 1886.06 1573.08 '
    '1963.66 1550.68 2007.79C1548.81 2011.52 1547.21 2014.99 1547.21 2015.39C1547.21 2015.79 '
    '1572.68 2016.06 1603.88 2016.06H1660.41L1661.88 2010.32C1664.68 2002.59 1669.08 1976.72 '
    '1671.48 1960.06C1673.74 1943.26 1673.74 1881.39 1671.48 1862.72C1662.94 1794.99 1648.68 '
    '1741.26 1625.34 1690.46C1622.81 1684.72 1621.21 1679.79 1621.74 1679.52C1622.41 1679.12 '
    '1626.14 1673.79 1630.14 1667.79C1659.21 1623.79 1677.08 1568.46 1686.14 1495.39C1688.54 '
    '1475.26 1688.54 1388.72 1686.14 1369.39C1679.74 1319.52 1672.01 1285.66 1659.21 1251.39C'
    '1653.88 1237.12 1639.74 1206.99 1633.74 1197.26L1630.81 1192.32L1640.94 1177.26C1672.01 '
    '1130.59 1690.14 1079.66 1697.21 1019.39C1700.41 993.255 1699.34 940.455 1695.34 914.322C'
    '1684.94 848.055 1660.54 787.255 1622.68 733.388C1602.94 705.255 1574.28 674.455 1549.21 '
    '654.455C1541.88 648.588 1535.34 643.255 1534.81 642.722C1534.14 642.188 1534.94 634.855 '
    '1536.54 626.589C1552.68 542.455 1552.14 437.522 1535.21 355.522C1520.54 284.055 1493.88 '
    '227.255 1459.48 194.455C1432.01 168.322 1404.01 157.122 1370.41 159.255C1293.34 163.788 '
    '1231.21 252.455 1206.68 392.188C1202.68 414.722 1199.21 441.122 1199.21 448.322C1199.21 '
    '451.122 1198.68 453.388 1198.01 453.388C1197.34 453.388 1192.14 450.722 1186.54 447.388C'
    '1127.08 412.188 1060.94 393.388 996.544 393.388C932.144 393.388 866.011 412.188 806.544 '
    '447.388C800.944 450.722 795.744 453.388 795.077 453.388C794.411 453.388 793.877 451.122 '
    '793.877 448.322C793.877 440.855 790.277 413.655 786.411 392.188C764.144 266.722 713.077 '
    '183.655 645.211 162.722C635.877 159.922 609.344 158.055 599.877 159.522Z'
    'M622.544 268.055C641.744 283.255 663.077 326.722 675.344 375.388C683.877 416.055 689.077 '
    '444.322 691.744 512.055L691.877 548.722L682.677 562.322L673.477 576.055H652.011C626.944 '
    '576.055 602.011 579.255 578.144 585.655C557.211 590.855 556.811 590.055 555.344 579.122C'
    '547.477 519.788 547.877 454.055 556.544 399.388C566.144 338.455 588.544 283.255 610.411 '
    '266.988C615.611 263.122 616.544 263.255 622.544 268.055Z'
    'M1382.81 267.122C1396.01 276.855 1410.54 302.722 1421.34 335.788C1443.08 401.922 1449.21 '
    '492.722 1437.74 579.122C1436.28 590.055 1435.88 590.855 1433.34 590.322C1414.94 585.655 '
    '1391.08 579.255 1366.14 576.055H1341.08L1319.61 576.055L1310.41 562.322L1301.21 548.722L'
    '1301.34 512.055C1301.61 460.322 1306.41 419.922 1317.88 374.988C1330.01 326.722 1351.48 '
    '283.255 1370.54 268.055C1376.54 263.255 1377.48 263.122 1382.81 267.122Z" fill="white"/>'
    '<path d="M975.877 938.189C946.944 940.989 939.077 942.055 925.21 944.855C902.677 949.522 '
    '872.544 959.922 851.61 970.189C778.81 1005.79 728.677 1065.12 713.344 1133.79C710.277 '
    '1147.39 709.877 1151.92 709.877 1174.86C709.877 1197.52 710.277 1202.46 713.21 1215.39C'
    '733.61 1305.12 816.277 1371.39 923.21 1383.52C946.41 1386.06 1046.68 1386.06 1069.88 '
    '1383.52C1155.74 1373.79 1229.61 1327.26 1262.81 1261.92C1271.61 1244.46 1275.88 1233.12 '
    '1279.88 1215.39C1282.81 1202.46 1283.21 1197.52 1283.21 1174.86C1283.21 1151.92 1282.81 '
    '1147.39 1279.74 1133.79C1257.48 1034.06 1160.68 955.522 1042.01 940.589C1026.54 938.722 '
    '986.01 937.122 975.877 938.189ZM1025.74 1010.72C1065.34 1014.99 1105.21 1029.12 1137.21 '
    '1050.46C1154.41 1061.92 1178.68 1085.92 1189.08 1101.66C1201.88 1121.12 1209.21 1140.99 '
    '1212.54 1165.12C1214.01 1176.19 1213.21 1184.59 1209.21 1202.46C1202.94 1229.12 1183.48 '
    '1256.99 1157.21 1276.46C1144.94 1285.39 1119.48 1298.32 1103.88 1303.39C1074.28 1312.86 '
    '1054.94 1314.59 985.877 1314.06C940.81 1313.66 932.81 1313.26 919.877 1310.86C875.744 '
    '1302.59 840.81 1284.99 815.477 1258.19C794.944 1236.59 785.61 1216.86 780.544 1184.99C'
    '778.277 1170.19 782.544 1145.66 791.21 1124.99C801.744 1099.79 828.944 1068.46 855.877 '
    '1050.46C887.077 1029.66 928.144 1014.86 965.877 1010.86C980.41 1009.26 1011.21 1009.26 '
    '1025.74 1010.72Z" fill="white"/>'
    '<path d="M945.61 1108.06C935.477 1113.52 928.41 1127.39 930.543 1137.66C932.943 1148.72 '
    '942.677 1159.92 957.877 1169.12C966.01 1174.06 966.543 1174.72 966.943 1179.66C967.21 '
    '1182.59 966.143 1190.99 964.677 1198.46C963.077 1205.79 961.877 1213.52 961.877 1215.66C'
    '962.01 1221.39 967.343 1230.72 972.943 1235.26C977.877 1239.26 978.81 1239.39 992.677 '
    '1239.79C1005.34 1240.19 1008.01 1239.92 1013.08 1237.52C1026.14 1231.12 1029.48 1219.39 '
    '1024.68 1196.86C1020.68 1178.06 1021.48 1175.12 1031.48 1169.39C1042.01 1163.26 1053.21 '
    '1152.46 1056.54 1145.12C1062.94 1131.12 1057.08 1115.26 1042.94 1107.92C1039.48 1106.19 '
    '1035.21 1105.39 1028.94 1105.39C1019.21 1105.39 1012.94 1107.66 1001.48 1114.99L994.943 '
    '1119.12L990.81 1116.59C973.877 1106.59 970.81 1105.39 960.543 1105.52C953.21 1105.52 '
    '949.21 1106.19 945.61 1108.06Z" fill="white"/>'
    '<path d="M621.878 953.255C598.278 960.722 580.678 978.055 571.611 1002.72C567.211 1014.46 '
    '565.078 1032.99 566.945 1042.99C571.345 1066.86 590.945 1088.59 613.211 1094.59C641.211 '
    '1101.92 662.145 1097.12 680.678 1078.72C691.478 1068.19 697.345 1058.99 703.211 1044.06C'
    '707.478 1033.52 707.745 1031.66 707.745 1016.72L707.878 1000.72L702.278 989.255C693.345 '
    '971.122 677.211 957.655 658.545 952.722C648.011 950.055 631.078 950.189 621.878 953.255Z" '
    'fill="white"/>'
    '<path d="M1334.01 952.855C1315.74 957.789 1299.48 971.389 1290.81 989.255L1285.21 1000.72L'
    '1285.34 1016.72C1285.34 1031.66 1285.61 1033.52 1289.88 1044.06C1295.74 1058.99 1301.61 '
    '1068.19 1312.41 1078.72C1330.94 1097.12 1351.88 1101.92 1379.88 1094.59C1396.01 1090.32 '
    '1412.14 1076.72 1419.88 1060.86C1426.54 1047.39 1428.14 1037.66 1426.01 1022.32C1421.08 '
    '987.255 1400.54 961.789 1370.01 952.855C1361.08 950.189 1343.74 950.189 1334.01 952.855Z" '
    'fill="white"/>'
    '</svg>'
)
_OLLAMA_RENDERER = None

def _ollama_renderer():
    global _OLLAMA_RENDERER
    if _OLLAMA_RENDERER is None:
        _OLLAMA_RENDERER = QSvgRenderer(QByteArray(OLLAMA_SVG.encode()))
    return _OLLAMA_RENDERER

_GEMINI_RENDERER = None

def _gemini_renderer():
    global _GEMINI_RENDERER
    if _GEMINI_RENDERER is None:
        _GEMINI_RENDERER = QSvgRenderer(QByteArray(GEMINI_STAR_SVG.encode()))
    return _GEMINI_RENDERER

def _detect_wayland():
    if os.environ.get("XDG_SESSION_TYPE") == "wayland":
        return True
    if os.environ.get("WAYLAND_DISPLAY"):
        return True
    if Path(f"/run/user/{os.getuid()}/wayland-0").exists():
        return True
    try:
        import subprocess
        sid = os.environ.get("XDG_SESSION_ID", "")
        if sid:
            out = subprocess.run(
                ["loginctl", "show-session", sid, "-p", "Type", "--value"],
                capture_output=True, text=True, timeout=2
            ).stdout.strip()
            return out == "wayland"
    except Exception:
        pass
    return False

IS_WAYLAND = _detect_wayland()

HANDY_PINK = "#E91E8C"


def run(cmd):
    return subprocess.run(cmd, capture_output=True, text=True)


def get_driver() -> str:
    try:
        return DRIVER_FILE.read_text().strip()
    except Exception:
        return "gemini"


def check_status():
    shortcuts_ok = (
        run(["pgrep", "-f", "talk2ai-keys"]).returncode == 0
        if IS_WAYLAND else
        run(["pgrep", "xbindkeys"]).returncode == 0
    )
    shortcuts_label = "talk2ai-keys" if IS_WAYLAND else "xbindkeys"
    driver = get_driver()
    driver_label = f"{driver} CLI"
    handy_ok = run(["pgrep", "-x", "handy"]).returncode == 0
    return {
        "Servicio":      run(["systemctl", "--user", "is-active", SERVICE]).stdout.strip() == "active",
        shortcuts_label: shortcuts_ok,
        "Handy DB":      HANDY_DB.exists(),
        driver_label:    run(["which", driver]).returncode == 0,
        "espeak-ng":     run(["which", "espeak-ng"]).returncode == 0,
        "_handy_ok":     handy_ok,
    }


def get_mode():
    try:
        return MODE_FILE.read_text().strip()
    except Exception:
        return "ai"


def get_model():
    try:
        return MODEL_FILE.read_text().strip()
    except Exception:
        return ""


def make_icon(mode, driver, all_ok, beat_scale=1.0):
    S = 64
    px = QPixmap(S, S)
    px.fill(QColor(0, 0, 0, 0))
    p = QPainter(px)
    p.setRenderHint(QPainter.RenderHint.Antialiasing)

    # Aplicar escala de latido centrada en el icono principal (círculo 48px)
    if beat_scale != 1.0:
        cx, cy = 24.0, 24.0
        p.translate(cx, cy)
        p.scale(beat_scale, beat_scale)
        p.translate(-cx, -cy)

    clip = QPainterPath()
    clip.addEllipse(QRectF(1, 1, 46, 46))
    p.setClipPath(clip)
    p.setPen(Qt.PenStyle.NoPen)

    if mode == "dictate":
        p.setBrush(QBrush(QColor(HANDY_PINK)))
        p.drawEllipse(1, 1, 46, 46)
        p.setClipping(False)
        p.setPen(QColor("white"))
        font = QFont("Sans Serif", 22)
        font.setBold(True)
        p.setFont(font)
        p.drawText(1, 1, 46, 46, Qt.AlignmentFlag.AlignCenter, "H")
    elif driver == "gemini":
        p.setBrush(QBrush(QColor("#0D0D1A")))
        p.drawEllipse(1, 1, 46, 46)
        p.setClipping(False)
        _gemini_renderer().render(p, QRectF(2, 2, 44, 44))
    elif driver == "ollama":
        p.setBrush(QBrush(QColor("#0D0D0D")))
        p.drawEllipse(1, 1, 46, 46)
        p.setClipping(False)
        _ollama_renderer().render(p, QRectF(5, 3, 38, 42))
    else:
        # Icono genérico: círculo con inicial del driver en mayúscula
        p.setBrush(QBrush(QColor("#333")))
        p.drawEllipse(1, 1, 46, 46)
        p.setClipping(False)
        p.setPen(QColor("white"))
        font = QFont("Sans Serif", 22)
        font.setBold(True)
        p.setFont(font)
        p.drawText(1, 1, 46, 46, Qt.AlignmentFlag.AlignCenter, driver[0].upper())

    # Resetear transformación para el punto de estado (posición fija)
    p.resetTransform()
    p.setPen(Qt.PenStyle.NoPen)
    p.setBrush(QBrush(QColor("white")))
    p.drawEllipse(43, 43, 18, 18)
    dot = QColor("#4CAF50") if all_ok else QColor("#F44336")
    p.setBrush(QBrush(dot))
    p.drawEllipse(45, 45, 14, 14)

    p.end()
    return QIcon(px)


def make_ai_icon(size=64):
    px = QPixmap(size, size)
    px.fill(Qt.GlobalColor.transparent)
    p = QPainter(px)
    p.setRenderHint(QPainter.RenderHint.Antialiasing)
    grad = QRadialGradient(size / 2, size / 2, size / 2)
    grad.setColorAt(0.0, QColor("#7C3AED"))
    grad.setColorAt(1.0, QColor("#1E3A8A"))
    p.setBrush(QBrush(grad))
    p.setPen(Qt.PenStyle.NoPen)
    p.drawEllipse(0, 0, size, size)
    font = QFont("sans-serif", int(size * 0.42), QFont.Weight.Bold)
    p.setFont(font)
    p.setPen(QColor("#FFFFFF"))
    p.drawText(QRectF(0, 0, size, size), Qt.AlignmentFlag.AlignCenter, "✦")
    p.end()
    return QIcon(px)


class DebugWindow(QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("talk2ai Debug — Preguntas y Respuestas")
        self.setWindowIcon(make_ai_icon())
        self.resize(750, 520)
        self._line_count = 0

        layout = QVBoxLayout(self)
        layout.setContentsMargins(8, 8, 8, 8)
        layout.setSpacing(6)

        self.text = QTextBrowser()
        self.text.setOpenExternalLinks(True)
        self.text.setStyleSheet(
            "QTextBrowser {"
            "  background: #0D0D1A;"
            "  color: #E0E0E0;"
            "  font-family: monospace;"
            "  font-size: 11pt;"
            "  border: 1px solid #333;"
            "}"
            "QTextBrowser a { color: #80DEEA; }"
        )
        layout.addWidget(self.text)

        btn_bar = QHBoxLayout()
        btn_bar.addStretch()
        btn_clear = QPushButton("Limpiar")
        btn_clear.setFixedWidth(90)
        btn_clear.clicked.connect(self._clear)
        btn_bar.addWidget(btn_clear)
        layout.addLayout(btn_bar)

    def _clear(self):
        self.text.clear()
        self._line_count = 0
        try:
            DEBUG_LOG_FILE.write_text("")
        except Exception:
            pass

    def load_all(self):
        self.text.clear()
        self._line_count = 0
        self._read_new_lines()

    def _read_new_lines(self):
        try:
            lines = DEBUG_LOG_FILE.read_text().splitlines()
        except Exception:
            return
        new_lines = lines[self._line_count:]
        if not new_lines:
            return
        self._line_count = len(lines)
        import html as _html
        for line in new_lines:
            parts = line.split("|", 2)
            if len(parts) != 3:
                continue
            ts, kind, text = parts
            try:
                ms = int(ts)
                if ms > 9_999_999_999:
                    dt = datetime.fromtimestamp(ms / 1000).strftime("%H:%M:%S") + f".{ms % 1000:03d}"
                else:
                    dt = datetime.fromtimestamp(ms).strftime("%H:%M:%S")
            except Exception:
                dt = ts

            if kind == "SEP":
                frag = '<span style="color:#2a2a3a">────────────────────────────────────────</span>'
            elif kind == "INFO":
                frag = (
                    f'<span style="color:#616161">[{dt}]</span>&nbsp;'
                    f'<span style="color:#9E9E9E">📋 {_html.escape(text)}</span>'
                )
            elif kind == "L":
                frag = (
                    f'<span style="color:#616161">[{dt}]</span>&nbsp;'
                    f'<span style="color:#FFB300">🔗</span>&nbsp;'
                    f'<a href="{_html.escape(text)}" style="color:#80DEEA;">{_html.escape(text)}</a>'
                )
            elif kind == "D":
                frag = (
                    f'<span style="color:#616161">[{dt}]</span>&nbsp;'
                    f'<span style="color:{HANDY_PINK}"><b>[Dictado]</b></span>&nbsp;'
                    f'<span style="color:#E0E0E0">{_html.escape(text)}</span>'
                )
            elif kind == "Q":
                frag = (
                    f'<span style="color:#616161">[{dt}]</span>&nbsp;'
                    f'<span style="color:#4FC3F7"><b>[Tú]</b></span>&nbsp;'
                    f'<span style="color:#E0E0E0">{_html.escape(text)}</span>'
                )
            elif kind == "A":
                frag = (
                    f'<span style="color:#616161">[{dt}]</span>&nbsp;'
                    f'<span style="color:#A5D6A7"><b>[IA]</b></span>&nbsp;'
                    f'<span style="color:#E0E0E0">{_html.escape(text)}</span>'
                )
            elif kind == "STAT":
                frag = (
                    f'<span style="color:#616161">[{dt}]</span>&nbsp;'
                    f'<span style="color:#FFD54F">{_html.escape(text)}</span>'
                )
            else:
                continue

            cursor = self.text.textCursor()
            cursor.movePosition(QTextCursor.MoveOperation.End)
            if not self.text.document().isEmpty():
                cursor.insertBlock()
            cursor.insertHtml(frag)
        sb = self.text.verticalScrollBar()
        sb.setValue(sb.maximum())


class StatusWorker(QObject):
    done = pyqtSignal(dict)

    def run(self):
        self.done.emit(check_status())


class TalkTray:
    def __init__(self, app):
        self.app = app
        self.tray = QSystemTrayIcon()
        self._status = {}
        self._all_ok = False
        self._checking = False
        self._processing = False
        self._beat_frame = 0
        self._debug_window = None
        self._ollama_models_cache = None
        self._build_menu()
        self.tray.setIcon(make_icon(get_mode(), get_driver(), False))
        self.tray.setContextMenu(self.menu)
        self.tray.show()

        TALK2AI_DIR.mkdir(exist_ok=True)
        MODE_FILE.touch(exist_ok=True)
        DRIVER_FILE.touch(exist_ok=True)
        self._watcher = QFileSystemWatcher([str(MODE_FILE), str(DRIVER_FILE)])
        self._watcher.fileChanged.connect(self._on_file_changed)
        if STATE_FILE.exists():
            self._watcher.addPath(str(STATE_FILE))
            try:
                self._processing = STATE_FILE.read_text().strip() == "processing"
            except Exception:
                pass
        if DEBUG_LOG_FILE.exists():
            self._watcher.addPath(str(DEBUG_LOG_FILE))
        if DEBUG_ENABLED_FILE.exists():
            self._debug_window = DebugWindow()
            self._debug_window.load_all()
            self._debug_window.show()

        self._beat_timer = QTimer()
        self._beat_timer.setInterval(90)
        self._beat_timer.timeout.connect(self._beat_step)
        if self._processing:
            self._beat_timer.start()

        self._async_check()

        self.timer = QTimer()
        self.timer.timeout.connect(self._async_check)
        self.timer.start(3000)

    def _build_menu(self):
        self.menu = QMenu()

        self.lbl_mode = self.menu.addAction("Modo: —")
        self.lbl_mode.setEnabled(False)

        self.menu.addSeparator()

        # Estado (filas dinámicas, se recalculan con check_status)
        self._status_rows = []
        self._status_cache = {}
        for _ in range(3):  # máximo 3 filas de 2 columnas
            act = self.menu.addAction("")
            act.setEnabled(False)
            self._status_rows.append(act)

        self.menu.addSeparator()

        lbl_driver = self.menu.addAction("  Driver IA:")
        lbl_driver.setEnabled(False)

        act_gemini = self.menu.addAction("🌟  Gemini")
        act_gemini.triggered.connect(lambda: self._set_driver("gemini"))

        self._ollama_menu = QMenu("🖥️  Ollama", self.menu)
        self._ollama_menu.aboutToShow.connect(self._on_ollama_menu_show)
        placeholder = self._ollama_menu.addAction("  Abre para cargar modelos")
        placeholder.setEnabled(False)
        self.menu.addMenu(self._ollama_menu)

        self.menu.addSeparator()

        act_g = self.menu.addAction("🤖  Modo IA           Alt+Super+G")
        act_g.triggered.connect(lambda: self._set_mode("ai"))

        act_h = self.menu.addAction("⌨️   Modo Dictado    Alt+Super+H")
        act_h.triggered.connect(lambda: self._set_mode("dictate"))

        act_ptt = self.menu.addAction("🎙️   Grabar / Parar      Ctrl+Space")
        act_ptt.triggered.connect(lambda: subprocess.Popen(["handy", "--toggle-transcription"]))

        act_stop_rec = self.menu.addAction("⏹️   Parar grabación")
        act_stop_rec.triggered.connect(self._stop_recording)

        act_stop = self.menu.addAction("⏸️   Detener audio      Ctrl+Alt+Q")
        act_stop.triggered.connect(lambda: subprocess.Popen(["pkill", "-f", "espeak-ng"]))

        self.menu.addSeparator()

        self.act_debug = self.menu.addAction("🔍  Debug Q&A")
        self.act_debug.setCheckable(True)
        self.act_debug.setChecked(DEBUG_ENABLED_FILE.exists())
        self.act_debug.triggered.connect(self._toggle_debug)

        self.menu.addSeparator()

        self.act_handy = self.menu.addAction("▶  Abrir Handy")
        self.act_handy.triggered.connect(self._ensure_handy)

        act_restart = self.menu.addAction("↺  Reiniciar servicio")
        act_restart.triggered.connect(lambda: subprocess.Popen(
            ["systemctl", "--user", "restart", SERVICE]))

        self.menu.addSeparator()

        session = "Wayland" if IS_WAYLAND else "X11"
        lbl_session = self.menu.addAction(f"  Sesión: {session}")
        lbl_session.setEnabled(False)

        self.menu.addSeparator()

        act_quit = self.menu.addAction("Salir")
        act_quit.triggered.connect(self.app.quit)

    def _on_file_changed(self, path):
        if path not in self._watcher.files():
            self._watcher.addPath(path)
        if path == str(STATE_FILE):
            self._on_state_changed()
        elif path == str(DEBUG_LOG_FILE):
            if self._debug_window and self._debug_window.isVisible():
                self._debug_window._read_new_lines()
        else:
            self._update_ui(get_mode(), get_driver(), self._status, self._all_ok)

    def _on_state_changed(self):
        try:
            state = STATE_FILE.read_text().strip()
        except Exception:
            state = "idle"
        was_processing = self._processing
        self._processing = (state == "processing")
        if self._processing and not was_processing:
            self._beat_frame = 0
            self._beat_timer.start()
        elif not self._processing and was_processing:
            self._beat_timer.stop()
            self._beat_frame = 0
            self._update_ui(get_mode(), get_driver(), self._status, self._all_ok)

    def _beat_step(self):
        self._beat_frame = (self._beat_frame + 1) % len(HEARTBEAT_FRAMES)
        scale = HEARTBEAT_FRAMES[self._beat_frame]
        self.tray.setIcon(make_icon(get_mode(), get_driver(), self._all_ok, beat_scale=scale))

    def _toggle_debug(self, checked):
        if checked:
            DEBUG_LOG_FILE.write_text("")
            DEBUG_ENABLED_FILE.touch()
            self._watcher.addPath(str(DEBUG_LOG_FILE))
            if self._debug_window is None:
                self._debug_window = DebugWindow()
            self._debug_window.load_all()
            self._debug_window.show()
            self._debug_window.raise_()
        else:
            DEBUG_ENABLED_FILE.unlink(missing_ok=True)
            if self._debug_window:
                self._debug_window.hide()
        self.act_debug.setChecked(checked)

    def _ensure_handy(self):
        def _do():
            if subprocess.run(["pgrep", "-x", "handy"], capture_output=True).returncode != 0:
                subprocess.Popen(["/home/gtx/.local/bin/handy"],
                                 stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        threading.Thread(target=_do, daemon=True).start()

    def _stop_recording(self):
        """Para la grabación de Handy. Si no responde en 2s, lo mata."""
        def _do():
            try:
                subprocess.run(["handy", "--toggle-transcription"],
                               capture_output=True, timeout=2)
            except subprocess.TimeoutExpired:
                subprocess.run(["pkill", "-9", "-x", "handy"], capture_output=True)
        threading.Thread(target=_do, daemon=True).start()

    def _get_ollama_host(self) -> str:
        try:
            return OLLAMA_HOST_FILE.read_text().strip()
        except Exception:
            return os.environ.get('TALK2AI_OLLAMA_HOST', 'http://127.0.0.1:11434')

    def _ask_ollama_host(self) -> bool:
        """Muestra un diálogo para introducir la URL del servidor Ollama.
        Devuelve True si el usuario confirmó, False si canceló."""
        current = self._get_ollama_host()
        url, ok = QInputDialog.getText(
            None,
            "Servidor Ollama",
            "URL del servidor Ollama\n(por defecto local: http://127.0.0.1:11434)",
            text=current,
        )
        if not ok or not url.strip():
            return False
        url = url.strip().rstrip('/')
        if not url.startswith('http'):
            url = 'http://' + url
        OLLAMA_HOST_FILE.write_text(url)
        self._ollama_models_cache = None
        return True

    def _on_ollama_menu_show(self):
        if not OLLAMA_HOST_FILE.exists():
            if not self._ask_ollama_host():
                return
        if self._ollama_models_cache is not None:
            self._populate_ollama_menu(self._ollama_models_cache)
        else:
            self._ollama_menu.clear()
            loading = self._ollama_menu.addAction("  Cargando modelos…")
            loading.setEnabled(False)
            threading.Thread(target=self._fetch_ollama_models, daemon=True).start()

    def _fetch_ollama_models(self):
        import json
        import urllib.request
        host = self._get_ollama_host()
        try:
            with urllib.request.urlopen(f'{host}/api/tags', timeout=5) as r:
                data = json.loads(r.read())
            models = [m['name'] for m in data.get('models', [])]
        except Exception:
            models = []
        self._ollama_models_cache = models
        QTimer.singleShot(0, lambda: self._populate_ollama_menu(models))

    def _populate_ollama_menu(self, models):
        self._ollama_menu.clear()
        host = self._get_ollama_host()
        lbl_host = self._ollama_menu.addAction(f"  🖥️  {host}")
        lbl_host.setEnabled(False)
        act_change = self._ollama_menu.addAction("  ⚙️  Cambiar servidor…")
        act_change.triggered.connect(self._change_ollama_host)
        self._ollama_menu.addSeparator()
        act_select = self._ollama_menu.addAction("  ▶  Activar Ollama como driver")
        act_select.triggered.connect(lambda: self._set_driver("ollama"))
        if not models:
            self._ollama_menu.addSeparator()
            na = self._ollama_menu.addAction("  ⚠  Servidor no disponible")
            na.setEnabled(False)
            return
        self._ollama_menu.addSeparator()
        lbl = self._ollama_menu.addAction("  Modelo:")
        lbl.setEnabled(False)
        active = self._get_driver_model("ollama")
        for name in models:
            mark = "✓" if name == active else "   "
            act = self._ollama_menu.addAction(f"  {mark}  {name}")
            act.triggered.connect(lambda checked, m=name: self._set_driver_model("ollama", m))

    def _change_ollama_host(self):
        if self._ask_ollama_host():
            self._ollama_menu.clear()
            loading = self._ollama_menu.addAction("  Cargando modelos…")
            loading.setEnabled(False)
            threading.Thread(target=self._fetch_ollama_models, daemon=True).start()

    def _get_driver_model(self, driver):
        f = TALK2AI_DIR / f"model-{driver}"
        try:
            return f.read_text().strip()
        except Exception:
            defaults = {"gemini": "gemini-2.5-flash-lite", "ollama": "qwen3.5:2b"}
            return defaults.get(driver, "")

    def _set_driver_model(self, driver, model):
        (TALK2AI_DIR / f"model-{driver}").write_text(model)
        if get_driver() == driver:
            MODEL_FILE.write_text(model)
        self._ollama_models_cache = None

    def _set_mode(self, mode):
        MODE_FILE.write_text(mode)
        self._update_ui(mode, get_driver(), self._status, self._all_ok)

    def _set_driver(self, driver: str):
        DRIVER_FILE.write_text(driver)
        self._update_ui(get_mode(), driver, self._status, self._all_ok)

    def _async_check(self):
        if self._checking:
            return
        self._checking = True
        worker = StatusWorker()
        worker.done.connect(self._on_status)
        threading.Thread(target=worker.run, daemon=True).start()

    def _on_status(self, status):
        self._checking = False
        self._handy_ok = status.pop("_handy_ok", False)
        self._status = status
        self._all_ok = all(status.values())
        self._update_ui(get_mode(), get_driver(), status, self._all_ok)

    def _update_ui(self, mode, driver, status, all_ok):
        if STATE_FILE.exists() and str(STATE_FILE) not in self._watcher.files():
            self._watcher.addPath(str(STATE_FILE))
        if not self._processing:
            self.tray.setIcon(make_icon(mode, driver, all_ok))

        model = get_model()
        if mode == "dictate":
            mode_label = "⌨️  Dictado"
        else:
            mode_label = f"🤖 {driver}  ·  {model}" if model else f"🤖 {driver}"
        ok_str = "Todo OK" if all_ok else "⚠ Hay problemas"
        self.tray.setToolTip(f"talk2ai  |  {mode_label}  |  {ok_str}")
        self.lbl_mode.setText(f"  Modo: {mode_label}")

        handy_ok = getattr(self, "_handy_ok", False)
        self.act_handy.setText("✓  Handy corriendo" if handy_ok else "▶  Abrir Handy")
        self.act_handy.setEnabled(not handy_ok)

        self._status_cache.update(status)
        labels = list(status.keys())
        for i, act in enumerate(self._status_rows):
            l1 = labels[i * 2] if i * 2 < len(labels) else None
            l2 = labels[i * 2 + 1] if i * 2 + 1 < len(labels) else None
            if l1 is None:
                act.setText("")
                continue
            parts = []
            for lbl in (l1, l2):
                if lbl:
                    sym = "✓" if self._status_cache.get(lbl) else "✗"
                    parts.append(f"{sym}  {lbl}")
            act.setText("  " + "      ".join(parts))


if __name__ == "__main__":
    import fcntl
    import time

    TALK2AI_DIR.mkdir(exist_ok=True)
    lock_file = open(TALK2AI_DIR / "tray.lock", "w")
    try:
        fcntl.flock(lock_file, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except OSError:
        sys.exit(0)

    app = QApplication(sys.argv)
    app.setQuitOnLastWindowClosed(False)

    for _ in range(30):
        if QSystemTrayIcon.isSystemTrayAvailable():
            break
        time.sleep(1)

    TalkTray(app)
    sys.exit(app.exec())
